[build]
target = "wasm32-unknown-unknown"
#rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'

[target.wasm32-unknown-unknown]
rustflags = [
  #"-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "--cfg", "getrandom_backend=\"wasm_js\""
]


#[unstable]
#build-std = ['std', 'panic_abort']

